### ISSUE TITLE
Feature request - separate effects from mod into an effect library mod

### ISSUE THREAD

**Issue by meeprdib** [Minecraft-LightLand/FruitsDelight#12]
I'd like to be able to use this mod as a required library for one of my projects; [Apotheosis Ascended](https://www.curseforge.com/minecraft/mc-mods/apotheosis-ascended), but I don't want to force the users into downloading Farmer's Delight and an addon for it. I was considering just leaving it as an optional dependency, but I feel like players would miss out on a lot if they didn't have the mod installed. Moving the effects from this mod into a separate library would give some nice utility to mod / modpack developers who're trying to use some interesting effects without adding any "content" mods.

**Comment by lcy0x1** [comment]
It's a first time I see someone being concerning over adding Farmer's Delight into their pack lol.

No.

**Comment by meeprdib** [comment]
Just trying to keep dependencies as unobtrusive as possible 👍 I respect your decision though.
