### ISSUE TITLE
Polish, European Spanish and European Portuguese translations

### ISSUE THREAD

**Issue by Pikamochzo** [Minecraft-LightLand/FruitsDelight#13]
I couldn't make a pull request, so here you have the translations
[es_es.json](https://github.com/user-attachments/files/17784944/es_es.json)
[pl_pl.json](https://github.com/user-attachments/files/17784945/pl_pl.json)
[pt_pt.json](https://github.com/user-attachments/files/17784946/pt_pt.json)

**Comment by lcy0x1** [comment]
Applied
