### ISSUE TITLE
Jams aren't part of the #forge:jams tag.

### ISSUE THREAD

**Issue by SlayDigger** [Minecraft-LightLand/FruitsDelight#16]
The Jams added by this mod (and ars nouveau flavours and delights for that matter) aren't part of the #forge:jams tag. This leads to incompatibility with Delightful, where its Nut Butter and Jam Sandwich can't be made using jams with this mod.
![image](https://github.com/user-attachments/assets/6e40e443-8314-440e-b07c-3e1768325875)

**Comment by lcy0x1** [comment]
That tag is not part of standard forge tags. Probably defined by Delightful. Still, I will add it to jams to improve compatibility

**Comment by SlayDigger** [comment]
Oh, I wasn't aware of that. Awesome, and thank you :)

**Comment by lcy0x1** [comment]
completed in 1.0.15
