### ISSUE TITLE
Tag needed

### ISSUE THREAD

**Issue by Mechalopa** [Minecraft-LightLand/FruitsDelight#2]
I think blueberry, cranberry and hawberry need to be registered in `forge:berries` tag. (used in farmer's delight)

**Comment by lcy0x1** [comment]
I will address this soon. But do you think Hawberry counts as berry?

**Comment by Mechalopa** [comment]
I didn't think including hawberry in `forge:berries` would cause any problems (at least of gameplay)
I would be fine with either :)

**Comment by lcy0x1** [comment]
fixed
