### ISSUE TITLE
1.19.2 and 1.20.1, fruit trees spawn too often

### ISSUE THREAD

**Issue by FluffiKiki** [Minecraft-LightLand/FruitsDelight#3]
Trees from Fruits Delight in versions 0.5.4 1.19.2 and 1.0.4 1.20.1 spawn too often. Spawn rates need to go way down, especially for biomes with less flora, like below (BOP Tundra and Vanilla Snow Plains)
![2024-02-02_12 59 38](https://github.com/Minecraft-LightLand/FruitsDelight/assets/42556991/0a1af094-f31b-48f3-90b3-5212bb5bb258)
![2024-02-02_12 59 50](https://github.com/Minecraft-LightLand/FruitsDelight/assets/42556991/de1d22a9-a7dd-42c1-9315-7bdee07454ab)

**Comment by lcy0x1** [comment]
I will address this issue in the next version

**Comment by FluffiKiki** [comment]
I'm not exactly sure how biomes and tags work, but I'm pretty sure since vanilla Snow plains and BOP Tundra share the same one, it should work. I started up a new world in my 1.19.2 world, and the trees seem to not overtake as much. I can actually see the tundra. Besides that, it looks all good.
![2024-02-05_20 47 03](https://github.com/Minecraft-LightLand/FruitsDelight/assets/42556991/b052c45e-0d13-4557-8d14-99ee9e691006)

**Comment by lcy0x1** [comment]
1.0.5 /0.5.5 should fix this
