### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Sephiroth91** [Minecraft-LightLand/FruitsDelight#5]
Minecraft: 1.19.2
Forge: 43.3.0
Server crashes randomly.
The log file says that the error comes from the library mod l2library. However, I don't have this library in my modpack. But I have the Fruits Delight mod in the modpack and the library, if I saw it correctly, is integrated into this mod. Therefore I don't know how to update the library because I can only use the version that was integrated into fruits delight

https://github.com/Minecraft-LightLand/L2Library/issues/5
[crash-2024-02-18_14.41.00-server.txt](https://github.com/Minecraft-LightLand/FruitsDelight/files/14336073/crash-2024-02-18_14.41.00-server.txt)

**Comment by lcy0x1** [comment]
[w](https://github.com/Minecraft-LightLand/L2Library/issues/5#issuecomment-1953097694)
Ah, I forgot to update it in Fruits Delight workspace. I will update it in next version. Anyway you should be able to fix it by installing L2Library separately. Your installation will take precedence over the the builtin library

**Comment by lcy0x1** [comment]
alternatively you can download Twilight Flavors & Delight, they got L2Library 1.9.7, which has this bug fixed

**Comment by lcy0x1** [comment]
fixed in 0.5.8
