### ISSUE TITLE
[Suggestion] more fruits and trees!

### ISSUE THREAD

**Issue by GreenForzeGaming** [Minecraft-LightLand/FruitsDelight#7]
Coconut : Palm = Beach
Dragon Fruit : Cactus = desert
Banana : Short green Palm = Jungle Edge
Star Fruit : Tree = Savannah
Black Berry : Bush = Old Growth Taiga
Strawberry : Bush = Plains
avocado : Tree = Savannah
Green Sour Apple : Tree = Plains
Grapefruit : Tree = Badlands

**Comment by lcy0x1** [comment]
not planned
